version: '3.8'

services:

    # PHP interpreter
    app:
        build:
            context: ./.docker
            dockerfile: Dockerfile
        image: php:8.7-fpm-alpine
        container_name: php
        restart: unless-stopped
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 80:80
            - 3000:3000
        volumes:
            - ./:/var/www/html
        networks:
            - default

    # MySQL database
    mysql:
        image: mysql/mysql-server:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql-data:/var/lib/mysql/
        networks:
            - default

    # MySQL database testing
    mysql-testing:
        image: mysql/mysql-server:8.0
        container_name: mysql-testing
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: homestead_testing
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: password
        tmpfs:
            - /var/lib/mysql:rw
        networks:
            - default

networks:
    default:
        driver: bridge

volumes:
    mysql-data:
        driver: local
